name: CD

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    runs-on: 'self-hosted'
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Stop running service
        run: docker compose down be --rmi local
      
      - name: Start service
        run: docker compose up be -d
      
